import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ArticleReference, ArticleStatus, TopicId, TOPICS, formatThaiDate, getTopic } from "@shared/editorial";
import { ArrowLeft, Check, FileImage, FilePenLine, Loader2, Plus, Save, Send, UploadCloud, RotateCcw } from "lucide-react";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";
import { Link, useLocation, useRoute } from "wouter";
import DashboardLayout from "@/components/DashboardLayout";

type FormState = {
  slug: string; title: string; excerpt: string; topic: TopicId; body: string;
  coverImageKey: string | null; coverImageUrl: string | null; coverAlt: string;
  videoUrl: string; references: ArticleReference[];
};

const emptyForm: FormState = { slug: "", title: "", excerpt: "", topic: "living", body: "", coverImageKey: null, coverImageUrl: null, coverAlt: "", videoUrl: "", references: [] };
type EditableArticle = Omit<FormState, "body" | "coverAlt" | "videoUrl"> & { body: string[]; coverAlt: string | null; videoUrl: string | null };

function toForm(article: EditableArticle): FormState {
  return { slug: article.slug, title: article.title, excerpt: article.excerpt, topic: article.topic, body: article.body.join("\n\n"), coverImageKey: article.coverImageKey, coverImageUrl: article.coverImageUrl, coverAlt: article.coverAlt || "", videoUrl: article.videoUrl || "", references: article.references || [] };
}

const statusCopy: Record<ArticleStatus, string> = { draft: "ฉบับร่าง", submitted: "รอตรวจสอบ", changes_requested: "ขอให้แก้ไข", approved: "อนุมัติแล้ว", published: "เผยแพร่แล้ว" };
const statusClass: Record<ArticleStatus, string> = { draft: "bg-[#eee8db] text-[#776a54]", submitted: "bg-[#e8dfc4] text-[#816522]", changes_requested: "bg-[#f4dfd5] text-[#9b4c2e]", approved: "bg-[#dfe7d8] text-[#426044]", published: "bg-[#cfe2d8] text-[#285b47]" };

function EditorShell({ children }: { children: React.ReactNode }) {
  const { user, loading } = useAuth();
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#f6f2e9]"><Loader2 className="animate-spin text-[#b8653d]" /></div>;
  if (!user) return <div className="grid min-h-screen place-items-center bg-[#f6f2e9] p-6 text-center"><div><p className="eyebrow">พื้นที่นักเขียน</p><h1 className="mt-4 font-serif-thai text-3xl">เข้าสู่ระบบเพื่อส่งบทความ</h1><Button onClick={() => startLogin()} className="mt-7 bg-[#243932]">เข้าสู่ระบบ</Button></div></div>;
  return <DashboardLayout>{children}</DashboardLayout>;
}

function ReviewActions({ id, status }: { id: number; status: ArticleStatus }) {
  const utils = trpc.useUtils();
  const review = trpc.articles.review.useMutation({ onSuccess: async () => { await utils.articles.adminList.invalidate(); toast.success("อัปเดตสถานะบทความแล้ว"); }, onError: (error) => toast.error(error.message) });
  const changeStatus = (next: "changes_requested" | "approved" | "published") => {
    const reviewNote = next === "changes_requested" ? window.prompt("เขียนคำแนะนำสำหรับผู้ส่งบทความ") || "" : "";
    if (next === "changes_requested" && !reviewNote.trim()) return;
    review.mutate({ id, status: next, reviewNote });
  };
  if (status !== "submitted" && status !== "approved") return null;
  return <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={review.isPending} onClick={() => changeStatus("changes_requested")} className="gap-1 border-[#b8653d]/30 text-[#9b4c2e]"><RotateCcw size={14} /> ส่งกลับแก้ไข</Button>{status === "submitted" ? <Button size="sm" disabled={review.isPending} onClick={() => changeStatus("approved")} className="gap-1 bg-[#557067] hover:bg-[#426057]"><Check size={14} /> อนุมัติ</Button> : null}<Button size="sm" disabled={review.isPending} onClick={() => changeStatus("published")} className="gap-1 bg-[#b8653d] hover:bg-[#9f4929]"><Send size={14} /> เผยแพร่</Button></div>;
}

function ReviewQueue({ enabled }: { enabled: boolean }) {
  const { data: queue, isLoading } = trpc.articles.reviewQueue.useQuery(undefined, { enabled });
  if (!enabled) return null;
  return <section className="mt-8 rounded-2xl border border-[#b8653d]/20 bg-[#fffaf0] p-5 md:p-7"><div className="flex items-end justify-between gap-3"><div><p className="eyebrow text-[#b8653d]">คิวตรวจสอบ</p><h2 className="mt-2 font-serif-thai text-2xl font-semibold text-[#243932]">บทความที่รอการตัดสินใจ</h2></div><span className="text-xs text-[#7b877f]">{queue?.length ?? 0} รายการ</span></div>{isLoading ? <div className="grid min-h-24 place-items-center"><Loader2 className="animate-spin text-[#b8653d]" /></div> : queue?.length ? <div className="mt-5 space-y-3">{queue.map((article) => <div key={article.id} className="rounded-xl border border-[#243932]/10 bg-white p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass[article.status as ArticleStatus]}`}>{statusCopy[article.status as ArticleStatus]}</span><span className="text-xs text-[#7b877f]">{article.authorName ? `โดย ${article.authorName}` : "บทความจากทีมงาน"}</span></div><h3 className="mt-2 font-serif-thai text-xl font-semibold text-[#243932]">{article.title}</h3><p className="mt-1 text-sm text-[#65736c]">{article.excerpt}</p></div><div className="flex shrink-0 flex-wrap gap-2"><Link href={`/editor/articles/${article.id}/preview`} className="inline-flex h-9 items-center gap-1 rounded-md border border-[#243932]/15 px-3 text-sm font-semibold text-[#243932]">ดูตัวอย่าง</Link><Link href={`/editor/articles/${article.id}`} className="inline-flex h-9 items-center gap-1 rounded-md border border-[#b8653d]/25 px-3 text-sm font-semibold text-[#b8653d]">ตรวจทาน</Link></div></div><div className="mt-4"><ReviewActions id={article.id} status={article.status as ArticleStatus} /></div></div>)}</div> : <p className="mt-5 text-sm text-[#7b877f]">ยังไม่มีบทความรอตรวจสอบ</p>}</section>;
}

function CommentModeration({ enabled }: { enabled: boolean }) {
  const utils = trpc.useUtils();
  const { data: comments, isLoading } = trpc.engagement.adminComments.useQuery(undefined, { enabled });
  const hide = trpc.engagement.hideComment.useMutation({ onSuccess: async () => { await utils.engagement.adminComments.invalidate(); toast.success("ซ่อนความคิดเห็นแล้ว"); }, onError: (error) => toast.error(error.message) });
  if (!enabled) return null;
  return <section className="mt-8 rounded-2xl border border-[#243932]/10 bg-[#fbf9f3] p-5 md:p-7"><div className="flex items-end justify-between gap-3"><div><p className="eyebrow">ดูแลชุมชน</p><h2 className="mt-2 font-serif-thai text-2xl font-semibold text-[#243932]">ความคิดเห็นล่าสุด</h2></div><span className="text-xs text-[#7b877f]">ซ่อนความคิดเห็นที่ไม่เหมาะสมได้</span></div>{isLoading ? <div className="grid min-h-24 place-items-center"><Loader2 className="animate-spin text-[#b8653d]" /></div> : comments?.length ? <div className="mt-5 space-y-3">{comments.map((comment) => <div key={comment.id} className="rounded-xl border border-[#243932]/10 bg-white p-4"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-[#243932]">{comment.authorName}</p><span className="text-xs text-[#7b877f]">{comment.status === "visible" ? "แสดงอยู่" : "ซ่อนแล้ว"}</span></div><p className="mt-2 text-sm leading-7 text-[#53645c]">{comment.body}</p>{comment.status === "visible" ? <Button type="button" variant="outline" size="sm" onClick={() => hide.mutate({ id: comment.id })} disabled={hide.isPending} className="mt-3 border-[#b8653d]/25 text-[#9b4c2e]">ซ่อนความคิดเห็น</Button> : null}</div>)}</div> : <p className="mt-5 text-sm text-[#7b877f]">ยังไม่มีความคิดเห็นจากผู้อ่าน</p>}</section>;
}

export function EditorDashboard() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const adminQuery = trpc.articles.adminList.useQuery(undefined, { enabled: isAdmin });
  const mineQuery = trpc.articles.myList.useQuery(undefined, { enabled: Boolean(user) && !isAdmin });
  const articles = isAdmin ? adminQuery.data : mineQuery.data;
  const isLoading = isAdmin ? adminQuery.isLoading : mineQuery.isLoading;
  return <EditorShell><section className="mx-auto max-w-5xl py-4 md:py-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">{isAdmin ? "โต๊ะทำงานบรรณาธิการ" : "พื้นที่นักเขียน"}</p><h1 className="mt-3 font-serif-thai text-3xl font-semibold text-[#243932] md:text-5xl">{isAdmin ? "บทความและร่องรอยความคิด" : "งานเขียนของฉัน"}</h1><p className="mt-3 text-sm text-[#65736c]">{isAdmin ? "ตรวจทานที่มาและตัดสินใจว่างานชิ้นใดพร้อมเผยแพร่" : "เขียนสิ่งที่อยากชวนคิด แล้วส่งให้ทีมงานตรวจสอบก่อนเผยแพร่"}</p></div><Link href="/editor/articles/new" className="button-ink w-fit"><Plus size={16} /> เขียนบทความใหม่</Link></div>
    <div className="mt-10 overflow-hidden rounded-2xl border border-[#243932]/10 bg-[#fbf9f3]">{isLoading ? <div className="grid min-h-52 place-items-center"><Loader2 className="animate-spin text-[#b8653d]" /></div> : articles?.length ? <div className="divide-y divide-[#243932]/10">{articles.map((article) => <div key={article.id} className="flex flex-col gap-4 px-5 py-5 md:px-7"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass[article.status as ArticleStatus]}`}>{statusCopy[article.status as ArticleStatus]}</span><span className="text-xs text-[#7b877f]">{getTopic(article.topic).label}</span>{isAdmin && article.authorName ? <span className="text-xs text-[#7b877f]">โดย {article.authorName}</span> : null}</div><h2 className="mt-2 truncate font-serif-thai text-xl font-semibold text-[#243932]">{article.title}</h2><p className="mt-1 text-xs text-[#7b877f]">แก้ไขล่าสุด {formatThaiDate(article.updatedAt.toString())}{article.reviewNote ? ` · หมายเหตุ: ${article.reviewNote}` : ""}</p></div><Link href={`/editor/articles/${article.id}`} className="inline-flex items-center gap-2 text-sm font-semibold text-[#b8653d]">{isAdmin ? "ตรวจทาน" : "เปิดแก้ไข"} <FilePenLine size={16} /></Link></div>{isAdmin ? <ReviewActions id={article.id} status={article.status as ArticleStatus} /> : null}</div>)}</div> : <div className="px-7 py-16 text-center"><FilePenLine className="mx-auto text-[#b8653d]" size={30} strokeWidth={1.4} /><p className="mt-4 font-serif-thai text-2xl">ยังไม่มีบทความในพื้นที่นี้</p><p className="mt-2 text-sm text-[#65736c]">เริ่มจากบทความหนึ่งชิ้น แล้วค่อย ๆ ปรับจนพร้อมส่งให้ทีมงานตรวจสอบ</p><Link href="/editor/articles/new" className="mt-6 inline-flex text-sm font-semibold text-[#b8653d]">เขียนบทความแรก</Link></div>}</div><ReviewQueue enabled={isAdmin} /><CommentModeration enabled={isAdmin} />
  </section></EditorShell>;
}

function articlePayload(form: FormState) { return { slug: form.slug.trim(), title: form.title.trim(), excerpt: form.excerpt.trim(), topic: form.topic, body: form.body.split(/\n\s*\n/).map((part) => part.trim()).filter(Boolean), coverImageKey: form.coverImageKey, coverImageUrl: form.coverImageUrl, coverAlt: form.coverAlt.trim() || null, videoUrl: form.videoUrl.trim(), references: form.references }; }
function readAsBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("ไม่สามารถอ่านไฟล์ภาพได้")); reader.onload = () => resolve(String(reader.result).split(",")[1] || ""); reader.readAsDataURL(file); }); }

export function EditorArticleForm() {
  const [isNewRoute] = useRoute("/editor/articles/new");
  const [, params] = useRoute("/editor/articles/:id");
  const isNew = Boolean(isNewRoute) || !params?.id;
  const id = Number(params?.id || 0);
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const adminCurrent = trpc.articles.getForEditor.useQuery({ id }, { enabled: !isNew && isAdmin });
  const authorCurrent = trpc.articles.myGet.useQuery({ id }, { enabled: !isNew && Boolean(user) && !isAdmin });
  const current = isAdmin ? adminCurrent.data : authorCurrent.data;
  const isLoading = isAdmin ? adminCurrent.isLoading : authorCurrent.isLoading;
  const [form, setForm] = useState<FormState>(emptyForm);
  const upload = trpc.media.uploadImage.useMutation({ onSuccess: ({ key, url }) => { setForm((prev) => ({ ...prev, coverImageKey: key, coverImageUrl: url })); toast.success("อัปโหลดภาพแล้ว"); }, onError: (error) => toast.error(error.message) });
  const adminCreate = trpc.articles.create.useMutation({ onSuccess: async ({ id: newId }) => { await utils.articles.adminList.invalidate(); toast.success("บันทึกบทความแล้ว"); setLocation(`/editor/articles/${newId}`); }, onError: (error) => toast.error(error.message) });
  const adminUpdate = trpc.articles.update.useMutation({ onSuccess: async () => { await utils.articles.adminList.invalidate(); await utils.articles.getForEditor.invalidate({ id }); toast.success("บันทึกการเปลี่ยนแปลงแล้ว"); }, onError: (error) => toast.error(error.message) });
  const myCreate = trpc.articles.myCreate.useMutation({ onSuccess: async ({ id: newId }) => { await utils.articles.myList.invalidate(); toast.success("บันทึกงานเขียนแล้ว"); setLocation(`/editor/articles/${newId}`); }, onError: (error) => toast.error(error.message) });
  const myUpdate = trpc.articles.myUpdate.useMutation({ onSuccess: async () => { await utils.articles.myList.invalidate(); await utils.articles.myGet.invalidate({ id }); toast.success("อัปเดตงานเขียนแล้ว"); }, onError: (error) => toast.error(error.message) });
  useEffect(() => { if (current) setForm(toForm(current as EditableArticle)); }, [current]);
  const saving = adminCreate.isPending || adminUpdate.isPending || myCreate.isPending || myUpdate.isPending;
  const set = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((prev) => ({ ...prev, [key]: value }));
  const addReference = () => set("references", [...form.references, { title: "", url: "", author: "", publisher: "", publishedAt: "", note: "" }]);
  const updateReference = (index: number, field: keyof ArticleReference, value: string) => set("references", form.references.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const save = (action: "draft" | "submit" | "publish") => (event: FormEvent) => { event.preventDefault(); const article = articlePayload(form); if (isAdmin) { if (isNew) adminCreate.mutate({ article, publish: action === "publish" }); else adminUpdate.mutate({ id, article, publish: action === "publish" }); } else if (isNew) myCreate.mutate({ article, action: action === "submit" ? "submit" : "draft" }); else myUpdate.mutate({ id, article, action: action === "submit" ? "submit" : "draft" }); };
  const onFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 5 * 1024 * 1024) { toast.error("ขนาดไฟล์ภาพต้องไม่เกิน 5 MB"); return; } try { upload.mutate({ filename: file.name, mimeType: file.type, base64: await readAsBase64(file) }); } catch (error) { toast.error(error instanceof Error ? error.message : "อัปโหลดภาพไม่สำเร็จ"); } };
  const editable = isNew || !current || current.status === "draft" || current.status === "changes_requested" || isAdmin;
  if (!isNew && isLoading) return <EditorShell><div className="grid min-h-80 place-items-center"><Loader2 className="animate-spin text-[#b8653d]" /></div></EditorShell>;
  if (!isNew && !current) return <EditorShell><div className="py-16 text-center"><p className="font-serif-thai text-2xl">ไม่พบบทความนี้หรือคุณไม่มีสิทธิ์เข้าถึง</p><Link href="/editor" className="mt-4 inline-flex text-sm font-semibold text-[#b8653d]">กลับไปพื้นที่งานเขียน</Link></div></EditorShell>;
  return <EditorShell><section className="mx-auto max-w-4xl py-4 md:py-8"><Link href="/editor" className="inline-flex items-center gap-2 text-sm font-semibold text-[#557067]"><ArrowLeft size={16} /> กลับไปงานเขียนทั้งหมด</Link><div className="mt-8 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="eyebrow">{isNew ? (isAdmin ? "บทความใหม่" : "ส่งบทความ") : statusCopy[current?.status as ArticleStatus]}</p><h1 className="mt-3 font-serif-thai text-3xl font-semibold text-[#243932] md:text-5xl">{isNew ? "เขียนสิ่งที่อยากชวนคิด" : isAdmin ? "ตรวจทานและปรับถ้อยคำ" : "งานเขียนของฉัน"}</h1>{!isAdmin && isNew ? <p className="mt-3 max-w-2xl text-sm leading-6 text-[#65736c]">บทความจะยังไม่เผยแพร่ทันที ทีมงานจะตรวจสอบเนื้อหา แหล่งอ้างอิง และความเหมาะสมก่อนเผยแพร่</p> : null}</div>{current?.status === "published" ? <Link href={`/articles/${current.slug}`} className="text-sm font-semibold text-[#b8653d]" target="_blank">เปิดหน้าสาธารณะ</Link> : null}</div>
    {current?.reviewNote && !isAdmin ? <div className="mt-6 rounded-xl border border-[#b8653d]/20 bg-[#f4dfd5] p-4 text-sm leading-6 text-[#713b2a]"><strong>คำแนะนำจากบรรณาธิการ:</strong> {current.reviewNote}</div> : null}
    <form className="mt-10 space-y-7 rounded-2xl border border-[#243932]/10 bg-[#fbf9f3] p-5 md:p-8" onSubmit={save("draft")}>
      <fieldset disabled={!editable} className="space-y-7"><div className="grid gap-6 md:grid-cols-[1fr_220px]"><div className="space-y-2"><Label htmlFor="title">ชื่อเรื่อง</Label><Input id="title" value={form.title} onChange={(event) => set("title", event.target.value)} placeholder="ชื่อเรื่องที่ชวนให้หยุดคิด" className="border-[#243932]/15 bg-white" required /></div><div className="space-y-2"><Label htmlFor="topic">หัวข้อ</Label><select id="topic" value={form.topic} onChange={(event) => set("topic", event.target.value as TopicId)} className="flex h-10 w-full rounded-md border border-[#243932]/15 bg-white px-3 text-sm">{TOPICS.map((topic) => <option key={topic.id} value={topic.id}>{topic.label}</option>)}</select></div></div>
      <div className="space-y-2"><Label htmlFor="slug">ลิงก์บทความ (ภาษาอังกฤษ)</Label><Input id="slug" value={form.slug} onChange={(event) => set("slug", event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ""))} placeholder="a-short-english-link" className="border-[#243932]/15 bg-white" required /><p className="text-xs text-[#7b877f]">ใช้ตัวอักษรอังกฤษ ตัวเลข และขีดกลาง เพื่อสร้างลิงก์ที่อ่านง่าย</p></div>
      <div className="space-y-2"><Label htmlFor="excerpt">คำโปรย</Label><Textarea id="excerpt" value={form.excerpt} onChange={(event) => set("excerpt", event.target.value)} placeholder="สรุปสิ่งที่ผู้อ่านจะได้จากบทความชิ้นนี้" className="min-h-24 border-[#243932]/15 bg-white" required /></div><div className="space-y-2"><Label htmlFor="body">เนื้อหาบทความ</Label><Textarea id="body" value={form.body} onChange={(event) => set("body", event.target.value)} placeholder="เขียนเนื้อหาเป็นย่อหน้า โดยเว้นหนึ่งบรรทัดระหว่างย่อหน้า" className="min-h-80 border-[#243932]/15 bg-white leading-7" required /><p className="text-xs text-[#7b877f]">เว้นหนึ่งบรรทัดเพื่อแยกย่อหน้าเมื่อแสดงผลบนหน้าสาธารณะ</p></div>
      <div className="rounded-xl border border-[#243932]/10 bg-[#f6f2e9] p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><p className="font-semibold text-[#243932]">ภาพปกบทความ</p><p className="mt-1 text-sm text-[#65736c]">รองรับ JPG, PNG, WEBP หรือ GIF ขนาดไม่เกิน 5 MB</p></div><label className="button-ink w-fit text-sm"><UploadCloud size={16} /> {upload.isPending ? "กำลังอัปโหลด" : "เลือกภาพ"}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={onFile} className="hidden" disabled={upload.isPending || !editable} /></label></div>{form.coverImageUrl ? <div className="mt-5 grid gap-4 md:grid-cols-[180px_1fr]"><img src={form.coverImageUrl} alt={form.coverAlt || "ตัวอย่างภาพปก"} className="aspect-[4/3] w-full rounded-lg object-cover" /><div className="space-y-2"><Label htmlFor="coverAlt">คำอธิบายภาพ (Alt text)</Label><Input id="coverAlt" value={form.coverAlt} onChange={(event) => set("coverAlt", event.target.value)} placeholder="อธิบายภาพอย่างกระชับ" className="border-[#243932]/15 bg-white" /></div></div> : <div className="mt-5 flex items-center gap-2 text-sm text-[#7b877f]"><FileImage size={16} /> ยังไม่ได้เลือกภาพปก ระบบจะใช้ภาพลวดลายพื้นฐานแทน</div>}</div>
      <div className="space-y-2"><Label htmlFor="video">URL คลิปวิดีโอประกอบ (ไม่บังคับ)</Label><Input id="video" type="url" value={form.videoUrl} onChange={(event) => set("videoUrl", event.target.value)} placeholder="YouTube หรือ Vimeo URL" className="border-[#243932]/15 bg-white" /></div>
      <div className="rounded-xl border border-[#243932]/10 bg-[#f6f2e9] p-5"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><p className="font-semibold text-[#243932]">แหล่งอ้างอิง</p><p className="mt-1 text-sm text-[#65736c]">ช่วยให้ทีมงานตรวจสอบที่มาได้ชัดเจนยิ่งขึ้น</p></div><button type="button" onClick={addReference} className="inline-flex items-center gap-2 text-sm font-semibold text-[#b8653d]"><Plus size={16} /> เพิ่มแหล่งอ้างอิง</button></div><div className="mt-5 space-y-5">{form.references.map((reference, index) => <div key={index} className="rounded-lg border border-[#243932]/10 bg-white p-4"><div className="flex justify-between"><p className="text-sm font-semibold">แหล่งอ้างอิง {index + 1}</p><button type="button" onClick={() => set("references", form.references.filter((_, itemIndex) => itemIndex !== index))} className="text-xs text-[#b8653d]">ลบ</button></div><div className="mt-3 grid gap-3 md:grid-cols-2"><Input value={reference.title} onChange={(event) => updateReference(index, "title", event.target.value)} placeholder="ชื่อบทความหรือแหล่งข้อมูล" className="border-[#243932]/15" /><Input type="url" value={reference.url} onChange={(event) => updateReference(index, "url", event.target.value)} placeholder="https://..." className="border-[#243932]/15" /><Input value={reference.author || ""} onChange={(event) => updateReference(index, "author", event.target.value)} placeholder="ผู้เขียน (ไม่บังคับ)" className="border-[#243932]/15" /><Input value={reference.publisher || ""} onChange={(event) => updateReference(index, "publisher", event.target.value)} placeholder="สำนักพิมพ์/เว็บไซต์ (ไม่บังคับ)" className="border-[#243932]/15" /><Input value={reference.publishedAt || ""} onChange={(event) => updateReference(index, "publishedAt", event.target.value)} placeholder="วันที่เผยแพร่ (ไม่บังคับ)" className="border-[#243932]/15" /><Input value={reference.note || ""} onChange={(event) => updateReference(index, "note", event.target.value)} placeholder="หมายเหตุ (ไม่บังคับ)" className="border-[#243932]/15" /></div></div>)}</div></div></fieldset>
      <div className="flex flex-wrap justify-end gap-3 border-t border-[#243932]/10 pt-6">{editable ? <><Button type="submit" variant="outline" disabled={saving} className="gap-2 border-[#243932]/20 bg-white text-[#243932]"><Save size={16} /> บันทึกฉบับร่าง</Button>{isAdmin ? <Button type="button" disabled={saving} onClick={(event) => save("publish")(event as unknown as FormEvent)} className="gap-2 bg-[#b8653d] hover:bg-[#9f4929]"><Send size={16} /> เผยแพร่บทความ</Button> : <Button type="button" disabled={saving} onClick={(event) => save("submit")(event as unknown as FormEvent)} className="gap-2 bg-[#b8653d] hover:bg-[#9f4929]"><Send size={16} /> ส่งให้ตรวจสอบ</Button>}</> : <span className="text-sm text-[#7b877f]">บทความกำลังรอการตรวจสอบ จึงยังแก้ไขไม่ได้</span>}</div>
    </form></section></EditorShell>;
}


export function EditorPreview() {
  const [, params] = useRoute("/editor/articles/:id/preview");
  const { user } = useAuth();
  const id = Number(params?.id || 0);
  const { data: article, isLoading } = trpc.articles.getForEditor.useQuery({ id }, { enabled: user?.role === "admin" && id > 0 });
  if (user?.role !== "admin") return <EditorShell><div className="py-16 text-center"><p className="font-serif-thai text-2xl">หน้านี้สงวนไว้สำหรับบรรณาธิการ</p><Link href="/editor" className="mt-4 inline-flex text-sm font-semibold text-[#b8653d]">กลับไปพื้นที่งานเขียน</Link></div></EditorShell>;
  if (isLoading) return <EditorShell><div className="grid min-h-80 place-items-center"><Loader2 className="animate-spin text-[#b8653d]" /></div></EditorShell>;
  if (!article) return <EditorShell><div className="py-16 text-center"><p className="font-serif-thai text-2xl">ไม่พบบทความ</p><Link href="/editor" className="mt-4 inline-flex text-sm font-semibold text-[#b8653d]">กลับไปคิวตรวจสอบ</Link></div></EditorShell>;
  const topic = getTopic(article.topic);
  return <EditorShell><section className="mx-auto max-w-4xl py-4 md:py-8"><div className="flex items-center justify-between gap-3"><Link href="/editor" className="inline-flex items-center gap-2 text-sm font-semibold text-[#557067]"><ArrowLeft size={16} /> กลับไปคิวตรวจสอบ</Link><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusClass[article.status as ArticleStatus]}`}>{statusCopy[article.status as ArticleStatus]}</span></div><header className="mt-10"><p className="eyebrow" style={{ color: topic.accent }}>{topic.label}</p><h1 className="mt-4 font-serif-thai text-4xl font-semibold leading-tight text-[#243932] md:text-6xl">{article.title}</h1><p className="mt-5 text-lg leading-9 text-[#65736c]">{article.excerpt}</p>{article.authorName ? <p className="mt-5 text-sm text-[#7b877f]">ผู้ส่ง: {article.authorName}</p> : null}</header>{article.coverImageUrl ? <img src={article.coverImageUrl} alt={article.coverAlt || article.title} className="mt-10 aspect-[16/8] w-full rounded-3xl object-cover" /> : null}<div className="article-prose mt-12">{article.body.map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div><section className="mt-12 rounded-2xl border border-[#243932]/10 bg-[#f6f2e9] p-6"><h2 className="font-serif-thai text-2xl font-semibold">แหล่งอ้างอิง</h2><div className="mt-4 space-y-3">{article.references.map((reference) => <a key={reference.url} href={reference.url} target="_blank" rel="noreferrer" className="block rounded-xl bg-white p-4 text-sm"><strong className="text-[#243932]">{reference.title}</strong><span className="mt-1 block text-[#65736c]">{reference.url}</span></a>)}</div></section><div className="mt-8 flex flex-wrap gap-3"><Link href={`/editor/articles/${article.id}`} className="button-ink"><FilePenLine size={16} /> เปิดตรวจทาน</Link><ReviewActions id={article.id} status={article.status as ArticleStatus} /></div></section></EditorShell>;
}
